# Generated by Django 2.0.5 on 2018-10-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
    ]
